import LenisProvider from "@/providers/LenisProvider";
import { NavigationProvider } from "@/providers/NavigationProvider";

import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import Navigation from "@/components/layout/Navigation";
import Preloader from "@/components/layout/Preloader";
import MouseFollowerCursor from "@/components/ui/MouseFollowerCursor";

import { inter, sora } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/mouse-follower@1/dist/mouse-follower.min.css"
        />
      </head>
      <body
        className={`${inter.variable} ${sora.variable} antialiased flex flex-col min-h-dvh`}
      >
        <MouseFollowerCursor />
        <LenisProvider>
          <NextIntlClientProvider>
            <NavigationProvider>
              <Preloader />
              <Navbar />
              <Navigation />
              <main className="flex-auto">{children}</main>
              <Footer />
            </NavigationProvider>
          </NextIntlClientProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
