import LenisProvider from "@/providers/LenisProvider";

import type { Metadata } from "next";

import Footer from "@/components/layout/Footer";

import { inter, sora } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${sora.variable} antialiased flex flex-col min-h-dvh`}
      >
        <LenisProvider>
          <main className="flex-auto">{children}</main>

          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
