import LenisProvider from "@/providers/LenisProvider";

import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

import Footer from "@/components/layout/Footer";

import { inter, sora } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={`${inter.variable} ${sora.variable} antialiased flex flex-col min-h-dvh`}
      >
        <LenisProvider>
          <NextIntlClientProvider>
            <main className="flex-auto">{children}</main>

            <Footer />
          </NextIntlClientProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
